#!/usr/bin/env bash
# This script displays the content of /etc/passwd in a story format
while IFS=: read -r user pass uid gid info home sh
do
    echo "The user ${user} is part of the ${gid} gang, lives in ${home} and rides ${sh}. ${uid}'s place is protected by the passcode ${pass}, more info about the user here: ${info}"
done < /etc/passwd
